tunnel: your-tunnel-id
credentials-file: /etc/cloudflared/creds/creds.json

ingress:
  - hostname: linkopsmlm.com
    service: http://ui.linkops-afterlife.svc.cluster.local:5173
  - hostname: linkopsmlm.com
    path: /api/*
    service: http://api.linkops-afterlife.svc.cluster.local:8000
  - service: http_status:404
