version: "3.9"

name: afterlife
services:
  proxy:
    image: caddy:2
    container_name: afterlife-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${ACME_EMAIL}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - frontend
      - backend
      - grafana
      - prometheus

  frontend:
    image: ${ACR_LOGIN_SERVER}/afterlife-frontend:${IMAGE_TAG}
    container_name: afterlife-frontend
    restart: unless-stopped
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/", "||", "exit", "1"]
      interval: 15s
      timeout: 5s
      retries: 10

  backend:
    image: ${ACR_LOGIN_SERVER}/afterlife-backend:${IMAGE_TAG}
    container_name: afterlife-backend
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=sqlite:////app/db/users.db
      - CORS_ORIGINS=https://${DOMAIN},http://localhost:5173
    volumes:
      - app_db:/app/db
      - app_data:/app/data
      - ./data/personas:/app/data/personas:ro
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8000/ping"]
      interval: 15s
      timeout: 5s
      retries: 10

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: afterlife-prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=30d
      - --web.enable-lifecycle
    depends_on:
      - backend
      - node-exporter
      - cadvisor

  grafana:
    image: grafana/grafana:11.1.4
    container_name: afterlife-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-change_me}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: afterlife-node-exporter
    restart: unless-stopped
    pid: host
    command:
      - --path.rootfs=/host
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)
    volumes:
      - /:/host:ro,rslave
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: afterlife-cadvisor
    restart: unless-stopped
    privileged: true
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro

  # Optional: Local TTS service for voice synthesis
  tts:
    image: rhasspy/wyoming-piper:latest
    container_name: afterlife-tts
    restart: unless-stopped
    ports:
      - "10200:10200"
    environment:
      - PIPER_VOICE=en_US-lessac-medium
    volumes:
      - tts_data:/data
    profiles: ["tts"]  # Optional profile - enable with --profile tts

volumes:
  app_db:
  app_data:
  caddy_data:
  caddy_config:
  prom_data:
  grafana_data:
  tts_data: