apiVersion: v1
kind: Secret
metadata:
  name: afterlife-secrets
  namespace: linkops-afterlife
type: Opaque
stringData:
  OPENAI_API_KEY: ""  # Set via kubectl or external secrets
  ELEVENLABS_API_KEY: ""
  DID_API_KEY: ""