global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "persona-server"
    metrics_path: /metrics  
    static_configs:
      - targets: ["host.docker.internal:8001"]
    scrape_interval: 5s

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

