apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-service.yaml
  - ui-deployment.yaml
  - ui-service.yaml
  - configmap.yaml
  - cleanup-cronjob.yaml

commonLabels:
  app: linkops-afterlife
  project: linkops