apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: linkops-afterlife
spec:
  replicas: 2
  selector:
    matchLabels:
      component: ui
  template:
    metadata:
      labels:
        component: ui
    spec:
      containers:
      - name: ui
        image: ghcr.io/shadow-link-industries/linkops-afterlife-ui:latest
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_BASE
          value: "/api"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"