apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkops-afterlife

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/shadow-link-industries/linkops-afterlife-api:dev
    target:
      kind: Deployment
      name: api
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/shadow-link-industries/linkops-afterlife-ui:dev
    target:
      kind: Deployment
      name: ui

configMapGenerator:
  - name: afterlife-config
    behavior: merge
    literals:
      - DOMAIN=dev.linkopsmlm.com

namePrefix: dev-

commonLabels:
  env: dev